### ISSUE TITLE
hello, plz add me a comiter.

### ISSUE THREAD

**Issue by ncross42** [dlang-tour/korean#2]
I'm working with @technykim

**Comment by sconeman** [comment]
me too :)

**Comment by ZHANITEST** [comment]
same working here!

**Comment by wilzbach** [comment]
@ZHANITEST welcome to the party (invitation is out)

@astonshnam your invitation was still pending. I resent it (otherwise you can also accept it at https://github.com/dlang-tour)

**Comment by Geod24** [comment]
Closing this as invitations have been sent.
If you guys are interested in a Seoul D meetup, shout me an email!
